# run pipeline again after
# 2024-10-21 11:06:23,360|[WARNING]|42213|8290169408|dlt|pipeline.py|run:694|The pipeline `run` method will now load the pending load packages. The data you passed to the run function will not be loaded. In order to do that you must run the pipeline again
rm -rf ~/.dlt/pipelines/